# Generated by Django 5.1.3 on 2025-05-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_address', '0002_billingaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='food_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
