# Generated by Django 5.1.3 on 2025-05-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_address', '0003_billingaddress_food_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='food_category_id',
        ),
    ]
