# Generated by Django 5.1.3 on 2025-05-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='category_id',
            new_name='food_category_id',
        ),
    ]
